Adds parser for Bates Visual Guide [bvg] #17
emory-libraries/ezpaarse-platforms pull request #273
Opened 2018-04-13 20:43 UTC by AGCooper

### What are you adding/fixing?
Name of parser, what files does, issue fixed, etc.
bvg, adds new parser
#### Awesome List for Reviewers of Parsers :star::star:
- [ ] fetch new branch to local repo 'git pull'
- [ ] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [ ] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [ ] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [ ] check output from parser directory:  'echo 'line from log' | ./parser.js
- [ ] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

2018-04-17 18:50 UTC, lisahamlett approved these changes

2018-04-17 21:31 UTC, eipeele requested changes
It doesn't seem like individual videos parse, unless I'm not clicking on the right link.  Links from the logs:
10.110.26.143 8fE2LzNczTBakN6 epeele [17/Apr/2018:17:28:25 -0400] "GET http://batesvisualguide.com:80/less/_init.less?siteId=119&page=multimediaplayer HTTP/1.1" 200 202256 http://batesvisualguide.com.proxy.library.emory.edu/MultimediaPlayer.aspx?multimediaid=6091082 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.26.143 8fE2LzNczTBakN6 epeele [17/Apr/2018:17:28:26 -0400] "GET http://batesvisualguide.com:80/combres.axd/multimedia-player-js/1918465767/ HTTP/1.1" 200 3991 http://batesvisualguide.com.proxy.library.emory.edu/MultimediaPlayer.aspx?multimediaid=6091082 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
10.110.26.143 8fE2LzNczTBakN6 epeele [17/Apr/2018:17:28:28 -0400] "GET http://batesvisualguide.com:80/combres.axd/main-master-js/516966675/ HTTP/1.1" 200 467077 http://batesvisualguide.com.proxy.library.emory.edu/MultimediaPlayer.aspx?multimediaid=6091082 Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

2018-04-17 22:29 UTC, AGCooper commented
@eipeele I think you are looking at the code behind the video. If you proxy this link, which should parse, you'll get the video instead of code: http://batesvisualguide.com:80/MultimediaPlayer.aspx?multimediaid=6091082

2018-04-18 13:10 UTC, eipeele approved these changes

2018-04-18 13:10 UTC, merged