Adds parser for Ministry Matters [mm] #286
emory-libraries/ezpaarse-platforms pull request #301
Opened 2018-06-18 22:53 UTC by AGCooper

### What are you adding/fixing?
mm, adds new parser

#### Awesome List for Reviewers of Parsers :star::star:
- [ ] fetch new branch to local repo 'git pull'
- [ ] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [ ] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [ ] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [ ] check output from parser directory:  'echo 'line from log' | ./parser.js
- [ ] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

2018-06-21 18:10 UTC, eipeele requested changes
1 )  There is a 'reader' that isn't being parsed.  Example URL:  https://www.ministrymatters.com:443/reader/9781426725845/

2018-06-25 19:59 UTC, lisahamlett commented
Elizabeth's note about the reader seems to be because it has a closing slash.

2018-06-25 20:00 UTC, lisahamlett approved these changes
Once you add the link for Elizabeth, I'm good.

2018-06-29 13:11 UTC, eipeele approved these changes

2018-06-29 13:11 UTC, merged