adding parsing for series 'Hermeneia Commentary Series'
emory-libraries/ezpaarse-platforms pull request #310
Opened 2018-07-18 16:54 UTC by eipeele

### What are you adding/fixing?
Adding parsing for series 'Hermeneia Commentary Series' according to Theology's request

#### Awesome List for Reviewers of Parsers :star::star:
- [ ] fetch new branch to local repo 'git pull'
- [ ] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [ ] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [ ] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [ ] check output from parser directory:  'echo 'line from log' | ./parser.js
- [ ] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

2018-07-18 17:52 UTC, AGCooper requested changes
- Does muse.jhu.edu.gate3.inist.fr need to be in the domains list?
- line 18 change to //.test from //.exec (semantic)
- this doesn't parse: https://muse.jhu.edu:443/browse
- this doesn't parse: https://muse.jhu.edu:443/search?action=browse&limit=format:journal&limit=subscription:y&min=1&max=10&t=format_facet_select

2018-07-19 18:57 UTC, lisahamlett requested changes
I'm not sure where I'm supposed to check this.  Searches don't work with the muse parser: https://muse.jhu.edu:443/search?action=browse&limit=format:journal&limit=subscription:y&min=1&max=10&t=format_facet_select but, they do work with the ebscohost parser.
Other than that and browse, it looks good to me.

2018-07-19 20:14 UTC, AGCooper approved these changes

2018-07-19 20:14 UTC, AGCooper approved these changes

2018-07-19 20:15 UTC, merged