Adds Parser for The Journal of Graduate Medical Education
emory-libraries/ezpaarse-platforms pull request #365
Opened 2019-03-26 20:19 UTC by lisahamlett

### What are you adding/fixing?
Added the parser requested in https://github.com/emory-libraries/ezpaarse-platforms/issues/260

#### Awesome List for Reviewers of Parsers :star::star:
- [ ] fetch new branch to local repo 'git pull'
- [ ] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [ ] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [ ] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [ ] check output from parser directory:  'echo 'line from log' | ./parser.js
- [ ] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

2019-03-26 20:56 UTC, AGCooper requested changes
- [x] change short name to jgme

- [x] make sure to disable debugger

- [x] Abstract with doi: https://www.jgme.org:443/doi/abs/10.4300/JGME-D-11-00027.1?=

- [x] Article / HTML needs doi: https://www.jgme.org:443/doi/full/10.4300/JGME-D-11-00027.1?=

- [x] Article / PDF needs doi: https://www.jgme.org:443/doi/pdf/10.4300/JGME-D-11-00027.1

- [x] TOC / HTML: https://www.jgme.org:443/toc/jgme/10/4s

- [x] These 2 could be one piece: match = /^\/doi\/full\/([0-9.]+)\/([a-zA-Z0-9.-]+)$/i.exec(path) and match = /^\/doi\/pdf\/([0-9.]+)\/([a-zA-Z0-9.-]+)$/i.exec(path)

- [x] What about: https://www.jgme.org:443/page/[name]

2019-04-16 22:01 UTC, AGCooper requested changes
Comment out the console.error for production.

2019-04-16 22:05 UTC, AGCooper approved these changes

2019-04-16 23:19 UTC, lisahamlett commented
I still need to comment out the console.error before merging

2019-04-19 18:40 UTC, merged