Adds Parser for Duxiu
emory-libraries/ezpaarse-platforms pull request #373
Opened 2019-04-16 19:07 UTC by lisahamlett

### What are you adding/fixing?
Name of parser, what files does, issue fixed, etc.

#### Awesome List for Reviewers of Parsers :star::star:
- [ ] fetch new branch to local repo 'git pull'
- [ ] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [ ] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [ ] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [ ] check output from parser directory:  'echo 'line from log' | ./parser.js
- [ ] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

2019-04-16 19:08 UTC, lisahamlett commented
This parser is not done!!!  I had to upload what I had in order to switch branches and work on reviews for Alex and Clare.

2019-04-17 14:02 UTC, CB987 requested changes

2019-04-17 14:02 UTC, CB987 commented on duxiu/test/duxiu.2019-04-16.csv
> +400271577283;097B8C533DF3A071F202C9E497E77C29;;PDF;PDF;http://book.duxiu.com:80/godowndoc.jsp?dxid=400271577283&d=097B8C533DF3A071F202C9E497E77C29
lines 38 through 41 please change the out-rtype from PDF to whatever it should be ;)

2019-04-17 19:54 UTC, CB987 approved these changes

2019-04-17 19:55 UTC, merged