Updates Parser for American Mathematical Society
emory-libraries/ezpaarse-platforms pull request #434
Opened 2019-07-01 22:54 UTC by lisahamlett

#### Awesome List for Reviewers of Parsers :star::star:
- [ ] fetch new branch to local repo 'git pull'
- [ ] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [ ] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [ ] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [ ] check output from parser directory:  'echo 'line from log' | ./parser.js
- [ ] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

2019-07-02 13:56 UTC, CB987 commented
- should "http://www.ams.org:80/books/memo/1149/memo1149.pdf" parse as BOOK, PDF?
- i might give this one "http://www.ams.org:80/books/memo/1051" TOC or REF? it's currently showing as article, but it's got toc, abstract, and citation info for a book. or that's too nitpicky, just let me know. :)  also "https://www.ams.org:443/books/simon/003"
- likewise "http://www.ams.org:80/journals/ecgd/2019-23-01/S1088-4173-2019-00330-8" is not the actual article, but the same metadata-type stuff, but about an article instead of a book
- should "http://www.ams.org:80/proc/2001-129-02/S0002-9939-00-05795-6/S0002-9939-00-05795-6.pdf" parse as ARTICLE, PDF?
- should "http://www.ams.org:80/epubsearch/servlet/PubSearch?f1=msc&v1=&co1=and&f2=title&v2=&co2=and&f3=fulltext&v3=&co3=and&f4=author&v4=barton&startmo=00&startyr=&endmo=00&endyr=&sperpage=30&ssort=d&sendit22=Search" parse as SEARCH, HTML?
-should "https://mathscinet.ams.org:443/mathscinet/search/journal/profile?groupId=4492" be REF with united 4492?
- would it be useful to use this "https://mathscinet.ams.org:443/leavingmsn?url=https://doi.org/10.1515/advgeom-2018-0013" to get the doi of the article they clicked on, even though it routes them away from ams to view the article? 

everything else looks great. seriously, let me know if i need to dial back the nitpickyness. my tendency to overthink is strong and if it's not necessary in the parsers i can resist. :)

2019-07-02 13:57 UTC, CB987 requested changes
please see comment in issue

2019-07-02 22:30 UTC, lisahamlett commented
- Nitpicking is fine.  I should do a better job writing parsers.  :)

CORRECTED:
- https://mathscinet.ams.org:443/mathscinet/search/journal/profile?groupId=4492 > REF, HTML
- https://mathscinet.ams.org:443/leavingmsn?url=https://doi.org/10.1515/advgeom-2018-0013 > ARTICLE, HTML with DOI
- http://www.ams.org:80/epubsearch/servlet/PubSearch > SEARCH, HTML
- http://www.ams.org:80/books/memo/1051 > TOC, HTML
- http://www.ams.org:80/journals/ecgd/2019-23-01/S1088-4173-2019-00330-8 > ABS, HTML
- http://www.ams.org:80/books/memo/1149/memo1149.pdf > BOOK PDF

UNCHANGED:
- http://www.ams.org:80/proc/2001-129-02/S0002-9939-00-05795-6/S0002-9939-00-05795-6.pdf redirects to http://www.ams.org:80/journals/proc/2001-129-02/S0002-9939-00-05795-6/S0002-9939-00-05795-6.pdf which does parse.  If we parse the first one, every result will parse twice.  So, I didn't parse it.

2019-07-03 16:50 UTC, CB987 approved these changes

2019-07-03 16:50 UTC, merged