Adds parser for Index of Medieval Art
emory-libraries/ezpaarse-platforms pull request #474
Opened 2019-10-01 17:13 UTC by lisahamlett

#### Awesome List for Reviewers of Parsers :star::star:
- [ ] fetch new branch to local repo 'git pull'
- [ ] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [ ] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [ ] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [ ] check output from parser directory:  'echo 'line from log' | ./parser.js
- [ ] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

### **NOTE:** JPGs are set to not show in the logs because some websites have a lot of images that show in the log, so the images themselves are unparsable.

2019-11-14 22:00 UTC, AGCooper requested changes
What about pages like this one? https://theindex-princeton-edu.proxy.library.emory.edu/i/8/4A/255/84A2558A-7D63-4D17-B6AE-F08AD680205E.jpg

2019-11-14 22:59 UTC, lisahamlett commented
As I mentioned in the description above, JPGs do not show in the logs.
This is my log for refreshing the JPG:

170.140.211.90 UIFpJba992Rpbj5 lhamlet [14/Nov/2019:17:09:20 -0500] "GET https://proxy.library.emory.edu:443/usage?find=lhamlet HTTP/1.1" 200 16723 https://login.proxy.library.emory.edu/admin Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.211.90 UIFpJba992Rpbj5 lhamlet [14/Nov/2019:17:57:39 -0500] "GET https://proxy.library.emory.edu:443/usage?find=lhamlet HTTP/1.1" 200 339 - Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.211.90 UIFpJba992Rpbj5 lhamlet [14/Nov/2019:17:57:41 -0500] "GET https://proxy.library.emory.edu:443/usage?find=lhamlet HTTP/1.1" 200 16723 - Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.211.90 UIFpJba992Rpbj5 lhamlet [14/Nov/2019:17:57:48 -0500] "GET https://proxy.library.emory.edu:443/usage?find=lhamlet HTTP/1.1" 200 16723 - Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted
170.140.211.90 UIFpJba992Rpbj5 lhamlet [14/Nov/2019:17:58:01 -0500] "GET https://proxy.library.emory.edu:443/usage?find=lhamlet HTTP/1.1" 200 16723 - Default+AlwaysProxy+MoreRestricted+Restricted+Unrestricted

2019-11-25 20:01 UTC, lisahamlett commented
This is ready for review.

2019-11-26 22:57 UTC, AGCooper approved these changes

2019-11-26 22:58 UTC, merged