Adds parser for The Medical Letter
emory-libraries/ezpaarse-platforms pull request #605
Opened 2020-01-10 00:54 UTC by lisahamlett

#### Awesome List for Reviewers of Parsers :star::star:
- [ ] fetch new branch to local repo 'git pull'
- [ ] checkout new branch to test 'git checkout --track origin/{nameofbranch}' / make sure you're on correct branch with 'git status'
- [ ] find proxied resource and look through it (this generates entries in the logs).  Try to go through everything in nav bar since this will likely have most of the domain changes.
- [ ] go to the logs on the main proxy server and grep for your username.  Use these lines to then test.
- [ ] check output from parser directory:  'echo 'line from log' | ./parser.js
- [ ] check manifest.json to make sure no information is missing
- [ ] review/approve/merge pull request based on findings

2020-01-27 21:40 UTC, CB987 requested changes
The only thing I found is this:

REF?PDF? (The only way to see the content is to download)
https://secure.medicalletter.org:443/downloads/1550b_table.pdf
https://secure.medicalletter.org:443/downloads/1546b_table.pdf

but you may have already seen and rejected that for parsing.

2020-01-27 21:48 UTC, lisahamlett commented
@CB987 Looks like there are tables and figures that can be downloaded, so I parsed it as SUPPL instead of REF.

2020-01-27 21:54 UTC, CB987 approved these changes

2020-01-28 16:58 UTC, merged

2020-01-28 17:16 UTC, libah commented
Looks good.